### PR TITLE
Fixed the example code and made bit clearer

### PR DESCRIPTION
**Pull request by mstahv**

### CODE REVIEW

**Comment by mstahv** [comment]
Something wrong in the ECA validation 🤔

Screenshot 2023-09-27 at 14 54 00

**Comment by mstahv** [comment]
Awesome, I assume I was the first 3rd party contributor 😎

**Comment by mstahv** [comment]
BTW. I wonder why I needed to do this configuration to get this Vaadin example/test to work?

https://github.com/mstahv/flow-crm-tutorial/blob/eclipse-serializer/src/main/java/com/example/application/data/service/CrmService.java#L28-L34

**Comment by mstahv** [comment]
Ah, figured it out. So with normal Serializer serialization/deserialization only works within single JVM process, unless those hints are given for "foundation". With TypedSerializer everything seems to just work, now which should I use?

And please don't write those docs, then I'm supposed to RTFM instead of asking directly from you 🤓

**Comment by fh-ms** [comment]
If possible, always use the normal Serializer. It is just faster, more secure and produces less overhead.

**Comment by fh-ms** [comment]
Feel always free to ask, even after we delivered the docs ;-)

**Pull request merged**
